services:
  db:
    image: postgres:17.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "15432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"
    volumes:
      - ./cache:/data
  backend:
    container_name: zapTable_backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./zapTable-backend
    depends_on:
      - db
  frontend:
    container_name: zapTable_frontend
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./zapTable-frontend:/usr/app
